### ISSUE TITLE
Json bundle cannot validate in HAPI test server

### ISSUE THREAD

**Issue by pdi-uk** [num-codex/odm2fhir#8] opened 2021-01-12 15:09 UTC
**Describe the bug**
Error messages on HAPI test server when trying to validate json-bundle gererated by ODMtoFHIR

**To Reproduce**
![grafik](https://user-images.githubusercontent.com/72730338/104331517-71e9d980-54ef-11eb-8208-97ec8e5f3b3d.png)
in Postman 
2. add json file as body
3. 3. Send

**Expected behavior**
Status 201 created

**Screenshots**
Status 412

Error Messages:

`        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "bdl-7: FullUrl must be unique in a bundle, or else entries with the same fullUrl must have different meta.versionId (except in history bundles) [(type = 'history') or entry.where(fullUrl.exists()).select(fullUrl & resource.meta.versionId).isDistinct()]",
            "location": [
                "Bundle",
                "Line 1, Col 2"
            ]
        }`

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox

**Comment by holger-stenzhorn** [comment] 2021-01-13 06:37
@pdi-uk: Can you perhaps provide us with the input ODM that provokes this error? From the provided error message it looks like you might tried to send the output of a single ODM2FHIR run several times to your FHIR server (as we currently generate a new, unique UUID for each resource during each run of ODM2FHIR).

**Comment by cerbelding** [comment] 2021-01-13 08:13
The `ODM2FHIR` app already has a built-in _HAPI FHIR_ validator, which ensures that invalid _FHIR_ resources are not added to the bundle.

When testing the method you described above with our dummy data output, the online validator only delivers errors/warnings of the following types:
- **Processing warning**: 
multiple warning regarding resource-properties that SHALL be filled (according to the default FHIR-Profile of this type, but not according to the NUM-Profile)
- **Processing Error**: 
unresolvable NUM-Profiles (therefore unchecked) and supposedly nonexistent codes (e.g. LOINC#19817-6 [which does exist](https://www.findacode.com/loinc/19817-6--complications.html))

I cannot reproduce the error you described. So it would be good to get a copy of your input-ODM, as @holger-stenzhorn already said.

**Comment by pdi-uk** [comment] 2021-01-13 14:20
this is our input ODM:


[TestGECCO_CDISC_ODM_2020-12-10_1140t.txt](https://github.com/num-codex/odm2fhir/files/5809109/TestGECCO_CDISC_ODM_2020-12-10_1140t.txt)

**Comment by cerbelding** [comment] 2021-01-13 14:39
Thanks! I will check the problem and come back to you tomorrow.

**Comment by holger-stenzhorn** [comment] 2021-01-13 15:01
@pdi-uk Admittedly, this does not really concern your reported issue but still... :-) Which version of the data dictionary did you actually import into REDCap to create the instruments in there? It looks like you used the quite outdated one from 23.10.2020 which sadly does not work correctly with the recent ODM2FHIR. ...or did you just accidentally provide here an ancient export from 10.12.2020 and you have a more recent one based on the data dictionary from 13.11.2020 or (even better) 11.12.2020?

**Comment by pdi-uk** [comment] 2021-01-14 10:18
The version information of the data dictionary is lost in RedCap after uploading, but I think we used the data dictionary from 13.11.2020. However, we will try again with the newest version of the data dictionary.

**Comment by cerbelding** [comment] 2021-01-14 10:53
You have to remember that if you update the data dictionary, the already filled in forms WILL NOT BE UPDATED!  

Changes can therefore only be determined in the forms edited afterwards.

**Comment by pdi-uk** [comment] 2021-01-14 11:33
We updated the data dictionary and created a new sample patient. The error mentionted above does not appear any more when trying to validate the bundle.

**Comment by cerbelding** [comment] 2021-01-14 11:35
Okay, thats good!
I will close the issue as it's solved.

**Closed by cerbelding** 2021-01-14 11:35 UTC
